In [ ]:
import numpy as np

arr = np.random.randint(1, 20, (3, 3))
print(arr)

[[ 5 15 17]
 [ 2 18 13]
 [ 1 17 16]]


In [ ]:
arr = np.random.randint(1,20,(5,5))
print(arr)
row_min = np.min(arr, axis=1)
row_max = np.max(arr, axis=1)
print(row_min)
print(row_max)

[[11  6 19  5 19]
 [18  9  2  4 16]
 [ 3 12 13 12 18]
 [10 13 12  2 18]
 [ 4  6  5 10 10]]
[5 2 3 2 4]
[19 18 18 18 10]


In [ ]:
vec = np.random.randint(1,20,10)
print(vec)
vec = np.sort(vec)
print(vec)

[14 12 17 12  5  5  7 11 10 14]
[ 5  5  7 10 11 12 12 14 14 17]


In [ ]:
arr = np.random.randint(1,20,(5,5))
values , counts  = np.unique(arr, return_counts=True)
print(values)
print(counts)

[ 0  1  2  3  5  7  9 11 13 14 15 16 17 18]
[2 3 2 1 1 2 2 1 1 4 1 1 2 2]


In [ ]:
arr = np.random.randint(1,20,(4,4))
# boolean indexing
arr[arr % 2 == 0] = 0 
print(arr)


[[19  0  0  9]
 [ 7 15 19  0]
 [ 0  0  3  7]
 [19  7  0  1]]


In [29]:
arr = np.array([1, 4, 9, 16, 25])
sqrt_arr = np.sqrt(arr)
print(sqrt_arr)

[1. 2. 3. 4. 5.]


In [20]:
import numpy as np

arr = np.random.randint(1, 20, (3, 3))
row_means = np.mean(arr, axis=1)
result = arr - row_means.reshape(3,1)
print(result)


[[-1.33333333  1.66666667 -0.33333333]
 [ 4.33333333 -4.66666667  0.33333333]
 [ 1.33333333 -4.66666667  3.33333333]]
