In [6]:
import numpy as np

arr = np.random.randint(0, 20, (3, 3))
print(arr)

[[ 5 15 17]
 [ 2 18 13]
 [ 1 17 16]]


In [13]:
arr = np.random.randint(0,20,(5,5))
print(arr)
row_min = np.min(arr, axis=1)
row_max = np.max(arr, axis=1)
print(row_min)
print(row_max)

[[11  6 19  5 19]
 [18  9  2  4 16]
 [ 3 12 13 12 18]
 [10 13 12  2 18]
 [ 4  6  5 10 10]]
[5 2 3 2 4]
[19 18 18 18 10]
